### ISSUE TITLE
Message is not displayed.

### ISSUE THREAD

**Issue by prathameshkhade** [Neutrino79/FileNinja-2.0#3]
@Neutrino79 

![Screenshot_20240529-093249_Brave](https://github.com/Neutrino79/FileNinja-2.0/assets/122447678/20dcc581-731f-4ad1-a20b-bea02958a8cc)

Message is not displayed after clicking on "Send Message" button

**Comment by Neutrino79** [comment]
Fixed the Send message success/fail status is not showing
@prathameshkhade 

 
<img width="766" alt="Screenshot 2024-05-29 at 2 11 40 PM" src="https://github.com/Neutrino79/FileNinja-2.0/assets/107453374/bb4678cc-b1f3-444e-8202-e3cb995ce744">
